# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z7GiJHhYQYSWooUAmrU_TkJh3gMzjuAD
"""

import pandas as pd
Abdulaziz={

     "FISH":[ "Topivoldiyev Abbos","Zafarov Bobur","Qodirov Javohir","Karimov Laziz "," Turg'unov Dilshod","Nematova Barchinoy ","Xosilova Ruxsora ",
             "Karimova Dilrabo ","Ahmedova Madina ","Mirkomilova Madina ",],
     "YOSHI":[ "19","22","21","20","13","18","15","16","17","19", ],
     "MAKTABI":['28-maktab','29-maktab','30-maktab','31-maktab','1-maktab','14-maktab',
                '18-maktab','26-maktab','21-maktab','27-maktab',],
     "JINSI":["erkak","erkak","erkak","erkak","erkak","Ayol ","Ayol ","Ayol ","Ayol ","Ayol ",  ],
     "MANZILI":[ "Farg'ona shaxar", "Andilon  shaxar","Namangan shaxar","Termz shahar","Jizzax shaxar",
                "Samarqand shaxar","Buxoro shaxar","Toshkent shaxar","Marg'ulon shaxar","Xojaobod shaxar",],


}
malumot=pd.DataFrame(Abdulaziz)
print(malumot)

filtr=malumot[malumot['JINSI']=='erkak']
print(filtr)

filtr=malumot[(malumot['JINSI']=='erkak')&(malumot['YOSHI']>'19')]
print(filtr)